-- MySQL Script generated by MySQL Workbench
-- mar. 05 mars 2019 21:34:40 EAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_anglais
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_anglais
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_anglais` DEFAULT CHARACTER SET utf8 ;
USE `db_anglais` ;

-- -----------------------------------------------------
-- Table `db_anglais`.`Annee_Universitaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Annee_Universitaire` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Annee_Universitaire` (
  `au_id` INT NOT NULL,
  `au_libelle` VARCHAR(45) NULL,
  `au_debut` DATE NULL,
  `au_fin` DATE NULL,
  PRIMARY KEY (`au_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Cycle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Cycle` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Cycle` (
  `cyc_id` INT NOT NULL,
  `cyc_libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`cyc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Niveau`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Niveau` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Niveau` (
  `niv_id` INT NOT NULL,
  `cyc_id` INT NOT NULL,
  `niv_libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`niv_id`, `cyc_id`),
  INDEX `fk_Niveau_Grades1_idx` (`cyc_id` ASC),
  CONSTRAINT `fk_Niveau_Grades1`
    FOREIGN KEY (`cyc_id`)
    REFERENCES `db_anglais`.`Cycle` (`cyc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Parcours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Parcours` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Parcours` (
  `prc_id` INT NOT NULL,
  `prc_libelle` VARCHAR(255) NULL,
  `niv_id` INT NOT NULL,
  PRIMARY KEY (`prc_id`),
  INDEX `fk_Parcours_Niveau1_idx` (`niv_id` ASC),
  CONSTRAINT `fk_Parcours_Niveau1`
    FOREIGN KEY (`niv_id`)
    REFERENCES `db_anglais`.`Niveau` (`niv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Période`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Période` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Période` (
  `per_id` INT NOT NULL,
  `au_id` INT NOT NULL,
  `niv_id` INT NOT NULL,
  `per_libellecourt` VARCHAR(45) NULL,
  `per_libellelong` VARCHAR(245) NULL,
  `per_debut` DATE NULL,
  `per_fin` DATE NULL,
  `per_aratrappage` TINYINT(4) NULL DEFAULT 0,
  PRIMARY KEY (`per_id`, `au_id`),
  INDEX `fk_Période_Niveau1_idx` (`niv_id` ASC),
  INDEX `fk_Période_Annee_Universitaire1_idx` (`au_id` ASC),
  CONSTRAINT `fk_Période_Niveau1`
    FOREIGN KEY (`niv_id`)
    REFERENCES `db_anglais`.`Niveau` (`niv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Période_Annee_Universitaire1`
    FOREIGN KEY (`au_id`)
    REFERENCES `db_anglais`.`Annee_Universitaire` (`au_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Utilisateur` (
  `uti_id` INT NOT NULL,
  `uti_login` VARCHAR(10) NULL,
  `uti_email` VARCHAR(255) NULL,
  `uti_passwd` TEXT NULL,
  `uti_type` TINYINT(4) NULL,
  PRIMARY KEY (`uti_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Professeur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Professeur` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Professeur` (
  `prof_id` INT NOT NULL,
  `prof_login` VARCHAR(45) NULL,
  `prof_password` LONGTEXT NULL,
  `prof_nom` VARCHAR(255) NULL,
  `prof_prenom` VARCHAR(255) NULL,
  `prof_adresse` LONGTEXT NULL,
  `prof_email` VARCHAR(255) NULL,
  `prof_contact` VARCHAR(45) NULL,
  `uti_id` INT NOT NULL,
  PRIMARY KEY (`prof_id`, `uti_id`),
  INDEX `fk_Professeur_Utilisateur1_idx` (`uti_id` ASC),
  CONSTRAINT `fk_Professeur_Utilisateur1`
    FOREIGN KEY (`uti_id`)
    REFERENCES `db_anglais`.`Utilisateur` (`uti_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Unite_Enseignement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Unite_Enseignement` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Unite_Enseignement` (
  `ue_id` INT NOT NULL,
  `Prc_id` INT NOT NULL,
  `ue_libelle` VARCHAR(45) NULL,
  `ue_type` VARCHAR(45) NULL,
  PRIMARY KEY (`ue_id`),
  INDEX `fk_Unite_Enseignement_Parcours1_idx` (`Prc_id` ASC),
  CONSTRAINT `fk_Unite_Enseignement_Parcours1`
    FOREIGN KEY (`Prc_id`)
    REFERENCES `db_anglais`.`Parcours` (`prc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Element_constitutif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Element_constitutif` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Element_constitutif` (
  `ec_id` INT NOT NULL,
  `ue_id` INT NOT NULL,
  `prof_id` INT NOT NULL,
  `ec_libelle` VARCHAR(255) NOT NULL,
  `ec_credit` INT NOT NULL,
  `ec_notation` INT NOT NULL,
  `ec_coefficient` DOUBLE NOT NULL,
  `ec_volumehoraire` VARCHAR(45) NULL,
  `ec_travailpresenciel` DOUBLE NOT NULL,
  `ec_travailpersonnel` DOUBLE NOT NULL,
  PRIMARY KEY (`ec_id`, `ue_id`, `prof_id`),
  INDEX `fk_Element_constitutif_Unite_Enseignement1_idx` (`ue_id` ASC),
  INDEX `fk_Element_constitutif_Professeur1_idx` (`prof_id` ASC),
  CONSTRAINT `fk_Element_constitutif_Unite_Enseignement1`
    FOREIGN KEY (`ue_id`)
    REFERENCES `db_anglais`.`Unite_Enseignement` (`ue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Element_constitutif_Professeur1`
    FOREIGN KEY (`prof_id`)
    REFERENCES `db_anglais`.`Professeur` (`prof_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`etudiant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`etudiant` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`etudiant` (
  `etd_id` INT NOT NULL,
  `etd_nom` VARCHAR(255) NOT NULL,
  `etd_prenom` VARCHAR(255) NULL,
  `etd_datenaissance` DATE NOT NULL,
  `etd_nationalité` VARCHAR(100) NOT NULL,
  `etd_adresse` LONGTEXT NOT NULL,
  `etd_email` VARCHAR(255) NULL,
  `etd_dernieretab` LONGTEXT NOT NULL,
  `etd_nomconjoint` LONGTEXT NULL,
  `etd_nompere` LONGTEXT NOT NULL,
  `etd_nommere` LONGTEXT NOT NULL,
  PRIMARY KEY (`etd_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Mention`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Mention` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Mention` (
  `mnt_id` INT NOT NULL,
  `mnt_intervalle` VARCHAR(5) NOT NULL,
  `mnt_libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mnt_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Prof_Ue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Prof_Ue` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Prof_Ue` (
  `ue_id` INT NOT NULL,
  `prof_id` INT NOT NULL,
  PRIMARY KEY (`ue_id`),
  INDEX `fk_Prof_Ue_Professeur1_idx` (`prof_id` ASC),
  CONSTRAINT `fk_Prof_Ue_Unite_Enseignement1`
    FOREIGN KEY (`ue_id`)
    REFERENCES `db_anglais`.`Unite_Enseignement` (`ue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prof_Ue_Professeur1`
    FOREIGN KEY (`prof_id`)
    REFERENCES `db_anglais`.`Professeur` (`prof_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Niveau_Etudiant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Niveau_Etudiant` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Niveau_Etudiant` (
  `etd_id` INT NOT NULL,
  `niv_id` INT NOT NULL,
  `au_id` INT NOT NULL,
  PRIMARY KEY (`etd_id`, `niv_id`, `au_id`),
  INDEX `fk_Niveau_Etudiant_Niveau1_idx` (`niv_id` ASC),
  INDEX `fk_Niveau_Etudiant_Annee_Universitaire1_idx` (`au_id` ASC),
  CONSTRAINT `fk_Niveau_Etudiant_etudiant1`
    FOREIGN KEY (`etd_id`)
    REFERENCES `db_anglais`.`etudiant` (`etd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Niveau_Etudiant_Niveau1`
    FOREIGN KEY (`niv_id`)
    REFERENCES `db_anglais`.`Niveau` (`niv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Niveau_Etudiant_Annee_Universitaire1`
    FOREIGN KEY (`au_id`)
    REFERENCES `db_anglais`.`Annee_Universitaire` (`au_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Examen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Examen` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Examen` (
  `exam_id` INT NOT NULL,
  `per_id` INT NOT NULL,
  `exam_libelle` VARCHAR(255) NULL,
  `exam_sessiontype` INT NULL,
  PRIMARY KEY (`exam_id`, `per_id`),
  INDEX `fk_Examen_Période1_idx` (`per_id` ASC),
  CONSTRAINT `fk_Examen_Période1`
    FOREIGN KEY (`per_id`)
    REFERENCES `db_anglais`.`Période` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Evaluation_Etudiant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Evaluation_Etudiant` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Evaluation_Etudiant` (
  `evale_id` INT NOT NULL,
  `etd_id` INT NOT NULL,
  `ec_id` INT NOT NULL,
  `exam_id` INT NOT NULL,
  `per_id` INT NOT NULL,
  `avale_evaluation` DOUBLE NOT NULL,
  `evale_creditobtenu` TINYINT(4) NULL DEFAULT 0,
  PRIMARY KEY (`evale_id`, `etd_id`, `ec_id`, `exam_id`, `per_id`),
  INDEX `fk_Evaluation_Etudiant_Element_constitutif1_idx` (`ec_id` ASC),
  INDEX `fk_Evaluation_Etudiant_etudiant1_idx` (`etd_id` ASC),
  INDEX `fk_Evaluation_Etudiant_Examen1_idx` (`exam_id` ASC, `per_id` ASC),
  CONSTRAINT `fk_Evaluation_Etudiant_Element_constitutif1`
    FOREIGN KEY (`ec_id`)
    REFERENCES `db_anglais`.`Element_constitutif` (`ec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluation_Etudiant_etudiant1`
    FOREIGN KEY (`etd_id`)
    REFERENCES `db_anglais`.`etudiant` (`etd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluation_Etudiant_Examen1`
    FOREIGN KEY (`exam_id` , `per_id`)
    REFERENCES `db_anglais`.`Examen` (`exam_id` , `per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_anglais`.`Moyenne_Ue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_anglais`.`Moyenne_Ue` ;

CREATE TABLE IF NOT EXISTS `db_anglais`.`Moyenne_Ue` (
  `moyue_id` INT NOT NULL,
  `etd_id` INT NOT NULL,
  `ue_id` INT NOT NULL,
  `moyue_val` DOUBLE NULL,
  `moyue_acquis` TINYINT(4) NULL,
  PRIMARY KEY (`moyue_id`, `etd_id`, `ue_id`),
  INDEX `fk_Moyenne_Ue_etudiant1_idx` (`etd_id` ASC),
  INDEX `fk_Moyenne_Ue_Unite_Enseignement1_idx` (`ue_id` ASC),
  CONSTRAINT `fk_Moyenne_Ue_etudiant1`
    FOREIGN KEY (`etd_id`)
    REFERENCES `db_anglais`.`etudiant` (`etd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Moyenne_Ue_Unite_Enseignement1`
    FOREIGN KEY (`ue_id`)
    REFERENCES `db_anglais`.`Unite_Enseignement` (`ue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
